# -*- coding: utf-8 -*-
"""lstmRainfall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOjBkjqxNzqZsLb_6a0K6wSZNkisykHl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping , ModelCheckpoint
from datetime import datetime
from matplotlib.patches import Patch
print(tf.__version__)
pd.set_option('display.max_columns',600)

from google.colab import files
upload = files.upload()

df = pd.read_csv('rainfall in india 1901-2015.csv')
print(df.shape)
print(df.head)
print(df.info())
print(df.describe())
print(df.dtypes)

df.plot(figsize=(12,6))
plt.show()
#march,may,june,sept

numeric_cols = df.select_dtypes(include=[np.number]).columns.difference(['index', 'YEAR'])
for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    df[col] = df[col].clip(lower,upper)

df.plot(figsize=(12, 6))
plt.title("Rainfall data after IQR capping & robust scaling")
plt.xlabel("Row index")
plt.ylabel("Scaled rainfall")
plt.show()

df.drop(columns=df.select_dtypes(include=[np.number]).columns, inplace=True)

print(df.isnull().sum())

numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
for column in numeric_columns:
    if df[column].isnull().sum() > 0:
        median_value = df[column].median()
        df[column].fillna(median_value, inplace=True)
        # print(f"{median_value:.2f}")
print(df.isnull().sum())

numeric_data = df.select_dtypes(include=['int64', 'float64'])
if not numeric_data.empty and numeric_data.shape[1] > 1:
    plt.figure(figsize=(16, 12))
    sns.heatmap(numeric_data.corr(), square=True, annot=True)
    plt.title("Feature Correlation Heatmap", fontsize=18, fontweight='bold')
    plt.tight_layout()
    plt.show()

feature_cols = [
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP",
    "OCT", "NOV", "DEC", "Jan-Feb", "Mar-May", "Jun-Sep", "Oct-Dec", "ANNUAL"
]
features = df[feature_cols].fillna(df[feature_cols].median())
scaler = StandardScaler()
scaled_data = scaler.fit_transform(features.values)
training_data_len = int(np.ceil(len(scaled_data) * 0.95))
training_data = scaled_data[:training_data_len]

look_back = 15
X_train, y_train = [], []
for i in range(look_back, training_data_len):
    X_train.append(training_data[i - look_back:i])
    y_train.append(training_data[i])

X_train = np.array(X_train)
y_train = np.array(y_train)

model = keras.models.Sequential([
    LSTM(64, return_sequences=True, input_shape=(look_back, len(feature_cols))),
    LSTM(64),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(len(feature_cols))
])
model.compile(optimizer='adam', loss='mse')

# es = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)
# history = model.fit(X_train, y_train,
#                     epochs=150,
#                     batch_size=16,
#                     validation_data=(X_train, y_train),
#                     callbacks=[es],
#                     verbose=1)
es = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    min_delta=1e-3,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    epochs=200,
    batch_size=16,
    validation_data=(X_train, y_train),
    callbacks=[es],
    verbose=1
)

subdivision = df['SUBDIVISION'].iloc[0]
pred_val = model.predict(X_train)
pred_val_inv = scaler.inverse_transform(pred_val)
y_val_inv = scaler.inverse_transform(y_train)
plt.figure(figsize=(10,5))
plt.plot(df['YEAR'].iloc[-len(pred_val):], y_val_inv[:,-1], label='Actual Annual')
plt.plot(df['YEAR'].iloc[-len(pred_val):], pred_val_inv[:,-1], label='Predicted Annual')
plt.xlabel('Year'); plt.ylabel('Rainfall (mm)')
plt.title(f'{subdivision} Annual Rainfall Prediction')
plt.legend()
plt.show()

future_preds = []
seq = scaled_data[-look_back:].copy()

for _ in range(15):
    pred = model.predict(seq.reshape(1, look_back, len(feature_cols)))
    future_preds.append(pred[0])
    seq = np.vstack([seq[1:], pred])

future_preds = scaler.inverse_transform(np.array(future_preds))
years = np.arange(df['YEAR'].iloc[-1] + 1, df['YEAR'].iloc[-1] + 16)
future_df = pd.DataFrame(future_preds, columns=feature_cols)
future_df['YEAR'] = years

print(future_df[['YEAR', 'ANNUAL']])

def loss_function(actual_values, target_value=2500):
   return np.mean((actual_values - target_value) ** 2)
targets = [2000, 2500, 3000]
losses = [loss_function(df['ANNUAL'], target) for target in targets]
plt.figure(figsize=(15, 10))
plt.subplot(2, 2, 1)
plt.plot(df['YEAR'], df['ANNUAL'], 'bo-', linewidth=2, markersize=6)
plt.title('Annual Values Over Time', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Annual Value')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
z = np.polyfit(df['YEAR'], df['ANNUAL'], 1)
p = np.poly1d(z)
plt.plot(df['YEAR'], p(df['YEAR']), "r--", alpha=0.7, label=f'Trend: y={z[0]:.2f}x+{z[1]:.2f}')
plt.legend()

plt.subplot(2, 2, 2)
plt.bar([str(target) for target in targets], losses, color=['skyblue', 'lightgreen', 'lightcoral'])
plt.title('Loss Function Values for Different Targets', fontsize=14, fontweight='bold')
plt.xlabel('Target Value')
plt.ylabel('Mean Squared Error Loss')
plt.grid(True, alpha=0.3)

for i, loss in enumerate(losses):
    plt.text(i, loss + max(losses)*0.01, f'{loss:.2f}', ha='center', va='bottom')

mean_value = df['ANNUAL'].mean()
deviations = df['ANNUAL'] - mean_value
squared_errors = deviations ** 2

plt.subplot(2, 2, 3)
plt.bar(df['YEAR'], squared_errors, color='orange', alpha=0.7)
plt.axhline(y=np.mean(squared_errors), color='red', linestyle='--', label=f'Mean Squared Error: {np.mean(squared_errors):.2f}')
plt.title('Squared Errors from Mean', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Squared Error')
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)

plt.subplot(2, 2, 4)
plt.hist(df['ANNUAL'], bins=8, alpha=0.7, color='purple', edgecolor='black')
for target in targets:
    plt.axvline(x=target, color='red' if target == 2500 else 'green' if target == 2000 else 'blue',
                linestyle='--', linewidth=2, label=f'Target: {target}')
plt.title('Distribution of Annual Values with Targets', fontsize=14, fontweight='bold')
plt.xlabel('Annual Value')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("Summary Statistics:")
print(f"Mean: {df['ANNUAL'].mean():.2f}")
print(f"Median: {df['ANNUAL'].median():.2f}")
print(f"Std Dev: {df['ANNUAL'].std():.2f}")
print(f"Min: {df['ANNUAL'].min():.2f}")
print(f"Max: {df['ANNUAL'].max():.2f}")
print(f"\nLoss values for different targets:")
for target, loss in zip(targets, losses):
    print(f"Target {target}: MSE Loss = {loss:.2f}")

# 1. Create a combined DataFrame for historical and future data for plotting
historical_annual = df[['YEAR', 'ANNUAL']].copy()
historical_annual['Type'] = 'Historical'

future_annual = future_df[['YEAR', 'ANNUAL']].copy()
future_annual['Type'] = 'Forecast'

combined_df = pd.concat([historical_annual, future_annual])

# 2. Calculate a simple trend for context (e.g., 10-year average)
recent_history = historical_annual[historical_annual['YEAR'] >= historical_annual['YEAR'].max() - 10]
historical_avg = recent_history['ANNUAL'].mean()

# 3. Create a clear, visually appealing plot
plt.figure(figsize=(12, 6))
plt.plot(historical_annual['YEAR'], historical_annual['ANNUAL'], color='steelblue', label='Historical Data', linewidth=2)
plt.plot(future_annual['YEAR'], future_annual['ANNUAL'], color='coral', linestyle='--', marker='o', label='Model Forecast', linewidth=2)

# Add a line for the recent historical average for context
plt.axhline(y=historical_avg, color='gray', linestyle=':', alpha=0.8, label=f'Avg of Last {len(recent_history)} Years')

plt.fill_between(future_annual['YEAR'], future_annual['ANNUAL'] * 0.95, future_annual['ANNUAL'] * 1.05, color='coral', alpha=0.2, label='Forecast Range (Approx.)')
plt.title('Temperature Forecast for the Next 5 Years', fontsize=16, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Annual Temperature (°C)') # Make sure the unit is clear!
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# 4. Print an easy-to-understand summary
print("🌤️  FORECAST SUMMARY\n")
print(f"Based on historical data up to {historical_annual['YEAR'].max()}, the model predicts:\n")

for index, row in future_annual.iterrows():
    year = int(row['YEAR'])
    temp = row['ANNUAL']
    diff_from_avg = temp - historical_avg

    # Add a simple text descriptor
    if diff_from_avg > 0.5:
        descriptor = "(Significantly warmer than recent average)"
    elif diff_from_avg > 0:
        descriptor = "(Warmer than recent average)"
    elif diff_from_avg > -0.5:
        descriptor = "(Near recent average)"
    else:
        descriptor = "(Cooler than recent average)"

    print(f"• {year}: {temp:.2f}°C {descriptor}")

print(f"\nComparison: The average temperature over the last {len(recent_history)} years was {historical_avg:.2f}°C.")

historical_data = df[['YEAR', 'ANNUAL']].copy()
historical_data['Type'] = 'Historical'
future_data = future_df[['YEAR', 'ANNUAL']].copy()
future_data['Type'] = 'Forecast'

combined_data = pd.concat([historical_data, future_data])
recent_avg = historical_data[historical_data['YEAR'] > historical_data['YEAR'].max() - 10]['ANNUAL'].mean()

# Create the visualization
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))

# Plot 1: Historical and Forecast Data
ax1.plot(historical_data['YEAR'], historical_data['ANNUAL'],
         color='#2E86AB', linewidth=2.5, label='Historical Temperature')
ax1.plot(future_data['YEAR'], future_data['ANNUAL'],
         color='#A23B72', linewidth=2.5, linestyle='--', marker='o', label='Forecasted Temperature')

# Add a reference line for the recent average
ax1.axhline(y=recent_avg, color='#F18F01', linestyle=':', linewidth=2,
            label=f'Recent 10-year Average ({recent_avg:.2f}°C)')

# Add a shaded area for the forecast period
ax1.axvspan(future_data['YEAR'].min() - 0.5, future_data['YEAR'].max() + 0.5,
            alpha=0.1, color='blue', label='Forecast Period')

ax1.set_title('Temperature Trends and 15-Year Forecast', fontsize=16, fontweight='bold', pad=20)
ax1.set_ylabel('Temperature (°C)', fontsize=12)
ax1.legend(loc='upper left')
ax1.grid(True, alpha=0.3)

# Plot 2: Bar chart showing temperature change from recent average
temp_change = future_data['ANNUAL'] - recent_avg
colors = ['#A23B72' if change >= 0 else '#2E86AB' for change in temp_change]

bars = ax2.bar(future_data['YEAR'], temp_change, color=colors, alpha=0.7)
ax2.axhline(y=0, color='black', linewidth=0.8, linestyle='-')
ax2.set_title('Projected Temperature Change Compared to Recent Average', fontsize=16, fontweight='bold', pad=20)
ax2.set_xlabel('Year', fontsize=12)
ax2.set_ylabel('Temperature Change (°C)', fontsize=12)


for bar, value in zip(bars, temp_change):
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height + 0.01,
             f'{value:+.2f}°C', ha='center', va='bottom', fontweight='bold')

ax2.grid(True, alpha=0.3)
legend_elements = [Patch(facecolor='#A23B72', label='Warmer than average'),
                   Patch(facecolor='#2E86AB', label='Cooler than average')]
ax2.legend(handles=legend_elements, loc='upper left')

plt.tight_layout()
plt.show()
print("="*60)
print("TEMPERATURE FORECAST SUMMARY (NEXT 15 YEARS)")
print("="*60)
print(f"\nBased on historical data up to {historical_data['YEAR'].max()}, our model predicts:\n")

avg_forecast = future_data['ANNUAL'].mean()
max_temp_year = future_data.loc[future_data['ANNUAL'].idxmax(), 'YEAR']
min_temp_year = future_data.loc[future_data['ANNUAL'].idxmin(), 'YEAR']

print(f"• Average temperature over next 15 years: {avg_forecast:.2f}°C")
print(f"• This is {avg_forecast - recent_avg:+.2f}°C compared to the recent 10-year average")
print(f"• Warmest year forecast: {max_temp_year} ({future_data['ANNUAL'].max():.2f}°C)")
print(f"• Coolest year forecast: {min_temp_year} ({future_data['ANNUAL'].min():.2f}°C)")

print(f"\nYear-by-Year Forecast:")
for _, row in future_data.iterrows():
    change = row['ANNUAL'] - recent_avg
    print(f"• {int(row['YEAR'])}: {row['ANNUAL']:.2f}°C ({change:+.2f}°C from average)")